# Generated by Django 3.1.4 on 2020-12-26 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worker', '0002_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='accept',
            field=models.BooleanField(default=False, verbose_name='Accept'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='denied',
            field=models.BooleanField(default=False, verbose_name='Denied'),
        ),
        migrations.AddField(
            model_name='task',
            name='text',
            field=models.TextField(default='text', verbose_name='Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_task', to=settings.AUTH_USER_MODEL, verbose_name='Worker'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_task', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
